### ISSUE TITLE
Desktop search behavior

### ISSUE THREAD

**Issue by ianfox01** [abell529/newsmag#1]
**Current behavior:**

- User must click the magnifying glass icon and the search slides open. Once clicked, the search input and a new button slide out to the left.

**Expected behavior**:

- Both the icon and the words "Search" should be clickable.
- When the "Search" link is clicked, the input field should slide out to left. Instead of generating a new "Search" button as in the current state, the existing Search and magnifying class should become the button wiht 1px outline to fire a search.
- In a future version, the appearance of the search button outline should occur via CSS transition. Fort his MVP, the button border can simply appear immediately on click.
- Search can be fired by hitting enter or clicking the search button
- Clicking outside of search box/input returns the search returns the box to its current state -- animation should occur in reverse order.
- Although it is not well represented in this mockup images below, the words "search" and the magnifying class should not shift position during state changes. The appearance of the outline around the button and the slide-left effect of the input should occur "around" the search text without causing it to move.

Mockups:

**Default state mockup:**
![image](https://github.com/abell529/newsmag/assets/84914929/23fe927b-b0a8-492e-a702-35c7a1291859)

**Active state mockup:**
![image](https://github.com/abell529/newsmag/assets/84914929/3734fbb8-ad2b-4770-9354-9d2c938dc72a)

**Comment by ianfox01** [comment]
From @abell529 via WebEx:


> The search change for desktop was a little trickier than I originally anticipated, but it works
>
> one issue is around 1220 window width, the button gets cut off by the white cut-off corner
>
> I can't move things in, because it lines up with "For the Media"
>![b606dfeb-9193-465c-924f-128158955abd](https://github.com/abell529/newsmag/assets/84914929/53e6b283-d739-448a-aab8-4041ea1dcefa)



@abell529, your latest mockup looks really good. A few minor tweaks for the search box on desktop:

- Can we adjust the size of the text input to align better with the button? I think adjusting the top/bottom padding to 16px (currently 12) and bumping the top position down 1px will do it.
- Can the placeholder text be "Enter a search term"
- Can the placeholder text be reduced 300 weight (currently 400)

Also, your concern about the cut interfering with the search box is noted. We will need to address that but I think we can create a separate issue and tackle a little later. I'll log it.

**Comment by abell529** [comment]
I think this is fixed now

**Comment by ianfox01** [comment]
@abell529 -- a few more tweaks required since the latest ground of changes for the desktop global nav.

- Can we please suppress the underline for links in the nav area? Both can probabaly be targeted at once via `.header-container a`
- The search input is no longer styled the way we want. It should be a 1px border with square edges that aligns with the button.
- The way the search input slides in makes it briefly visible behind the button as it animates. Instead we want to the box to appear to "grow" from the left side of the button.

**Comment by ianfox01** [comment]
Documenting the conversation that we had yesterday: In order for this to animate and be accessible, we will combine the button and input into a single unit -- i.e., no space between the two elements.

This is similar to the behavior on the main TU website, but we will restyle to match the news/magazine design.

**Comment by ianfox01** [comment]
This is coming together, a few new pieces of feedback:

- The word "Search" and the icon should have a pointer cursor on hover. This should apply to both the inactive and focused versions (e.g., both when the search is open, and closed)
- When the search is open, the button background should should have a gold background with black text on hover.
- Ideally, when then the search closes, it should animate closed in reverse of the way it opens up. Same as the effect currently on towson.edu
